# Use Node.js 14 LTS as the base image
FROM node:20-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

ARG A_DB_DATABASE
ARG A_DB_USERNAME
ARG A_DB_PASSWORD
ARG A_DB_HOST
ARG A_DB_PORT
ARG A_DB_DIALECT

ARG A_JWT_SECRET  
ARG A_SESSION_SECRET 

ARG A_BREVO_HOST
ARG A_BREVO_PORT
ARG A_BREVO_USER
ARG A_BREVO_PASS
ARG A_EMAIL_USER

ARG A_FRONTEND_URL
ARG A_STRIPE_SECRET_KEY
ARG A_PAYMENT_REDIRECT_URL

ARG A_CLERK_DOMAIN
ARG A_CLERK_CLIENT_ID
ARG A_CLERK_CLIENT_SECRET
ARG A_CLERK_ORG

ENV APPLICATION_NAME="X Project"
ENV PORT=5000

ENV DB_DATABASE=${A_DB_DATABASE}
ENV DB_USERNAME=${A_DB_USERNAME}
ENV DB_PASSWORD=${A_DB_PASSWORD}
ENV DB_HOST=${A_DB_HOST}
ENV DB_PORT=${A_DB_PORT}
ENV DB_DIALECT=${A_DB_DIALECT}

ENV JWT_SECRET=${A_JWT_SECRET}
ENV SESSION_SECRET=${A_SESSION_SECRET}

ENV BREVO_HOST=${A_BREVO_HOST}
ENV BREVO_PORT=${A_BREVO_PORT}
ENV BREVO_USER=${A_BREVO_USER}
ENV BREVO_PASS=${A_BREVO_PASS}

ENV EMAIL_USER=${A_EMAIL_USER}
ENV FRONTEND_URL=${A_FRONTEND_URL}

ENV STRIPE_SECRET_KEY=${A_STRIPE_SECRET_KEY}
ENV PAYMENT_REDIRECT_URL=${A_PAYMENT_REDIRECT_URL}

ENV CLERK_DOMAIN=${A_CLERK_DOMAIN}
ENV CLERK_CLIENT_ID=${A_CLERK_CLIENT_ID}
ENV CLERK_CLIENT_SECRET=${A_CLERK_CLIENT_SECRET}
ENV CLERK_ORG=${A_CLERK_ORG}

ENV MAX_LOGIN_ATTEMPTS_COUNT=5
ENV LOCK_DURATION_IN_MINUTES=10
ENV OTP_VALIDATE_TIME=15
ENV DEFAULT_LANGUAGE=EN

ENV REF_DISCOUNT=50
ENV PROMO_DISCOUNT=10
ENV REF_COMISSION=10

# Install dependencies
RUN npm install

# Copy the rest of the application code7
COPY . .

# Expose the port that your app runs on
EXPOSE 5000

# Command to run your app
CMD ["node", "src/api/app.js"]

